
RUN_STRINGS = (
    "Now you see me, now you don't."
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = (
    "CgACAgQAAxkBAAILHWBPN8dL8NvxZ9tUfr3_4SdPGqgjAAJeAgACQQrNUlM24z1ISCsTHgQ",
    "CgACAgUAAxkBAAILLWBPPY1oNbS_7IErvTnSjD-7ERotAAJVAQACbtPYVrtCdh7pOSi6HgQ",
    "CgACAgQAAxkBAAILLmBPPY7bkDGWKszfehdSJ7RpW-7vAAJoCAACVkPRUQRXQgysd04VHgQ",
) 

SLAP_MIKU_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!"
    ])

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  #No game no life reference
    "Shut up {user2}, you are just {user2}.",  #No game no life reference
    "{user1} hits {user2} with Aka si anse!",  #No game no life reference
    "@NeoTheKitty scratches {user2}",  #Pixels pet cat - @NeoTheKitty 
    "Majin buu ate {user2}",  #Dbz
    "Goblin slayer slays {user2}",  #Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAAILM2BPPcztLjOKpX9lI6rqcJAf25phAAIyAgACXPW0UUEs74rXY7jHHgQ",
    "CgACAgQAAxkBAAILNGBPPc1X9A5WjSWny42TbvirITrYAAI6AgAC_hiMUsLYno0iqBsKHgQ",
    "CgACAgQAAxkBAAILNWBPPc2RwJLSld87q_QgacpiSIPoAAKFAgACa0hlUraGjbF-UlCxHgQ",
    "CgACAgQAAxkBAAILNmBPPc41VKh_5CSXiwFmLF94kt3PAAJlAgAC0xqMUgP_95WKxNyXHgQ",
    "CgACAgQAAxkBAAILN2BPPc790mPflEPaIaSLQO8UzaySAAIeAgACT3I8UIWFwhXak7MMHgQ",
    "CgACAgQAAxkBAAILOGBPPc6zjXtyaqYPS24XaWZBf51KAAJmAgACv2c9UvSqOBstdD43HgQ",
    "CgACAgQAAxkBAAILOWBPPc4bJIVehOvJ4nWEgZKiL33fAAJYAgACvTY1UhQnTgq4A5bzHgQ",
    "CgACAgQAAxkBAAILOmBPPdA2q6CUTY2Wvh147ZK5hS7fAAIiAgAClkjVUoGXNybyoMMFHgQ",
    "CgACAgQAAxkBAAILO2BPPdFcDMZLDbm2MmuHneRe72lfAAIjAgACNyiMUovAWkknFH7PHgQ",
    "CgACAgQAAxkBAAILPGBPPdHnzGgJSgxPAAF1VjxqVVgU8gACXAIAAg2OhFIv0IWYDryVzh4E",
    "CgACAgQAAxkBAAILPWBPPdE8HggjgaYISBbAXEucZ6QaAAK1AgACrxdcUkpC4d0BLZRfHgQ",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [['⌐■', '■'], [' ͠°', ' °'], ['⇀', '↼'], ['´• ', ' •`'], ['´', '`'],
        ['`', '´'], ['ó', 'ò'], ['ò', 'ó'], ['⸌', '⸍'], ['>',
                                                         '<'], ['Ƹ̵̡', 'Ʒ'],
        ['ᗒ', 'ᗕ'], ['⟃', '⟄'], ['⪧', '⪦'], ['⪦', '⪧'], ['⪩', '⪨'], ['⪨', '⪩'],
        ['⪰', '⪯'], ['⫑', '⫒'], ['⨴', '⨵'], ['⩿', '⪀'], ['⩾', '⩽'], ['⩺', '⩹'],
        ['⩹', '⩺'], ['◥▶', '◀◤'], ['◍', '◎'], ['/͠-', '┐͡-\\'], ['⌣', '⌣”'],
        [' ͡⎚', ' ͡⎚'], ['≋'], ['૦ઁ'], ['  ͯ'], ['  ͌'], ['ළ'], ['◉'], ['☉'],
        ['・'], ['▰'], ['ᵔ'], [' ﾟ'], ['□'], ['☼'], ['*'], ['`'], ['⚆'], ['⊜'],
        ['>'], ['❍'], ['￣'], ['─'], ['✿'], ['•'], ['T'], ['^'], ['ⱺ'], ['@'],
        ['ȍ'], ['  '], ['  '], ['x'], ['-'], ['$'], ['Ȍ'], ['ʘ'], ['Ꝋ'],
        [''], ['⸟'], ['๏'], ['ⴲ'], ['◕'], ['◔'], ['✧'], ['■'], ['♥'], [' ͡°'],
        ['¬'], [' º '], ['⨶'], ['⨱'], ['⏓'], ['⏒'], ['⍜'], ['⍤'], ['ᚖ'], ['ᴗ'],
        ['ಠ'], ['σ'], ['☯']]

MOUTHS = [['v'], ['ᴥ'], ['ᗝ'], ['Ѡ'], ['ᗜ'], ['Ꮂ'], ['ᨓ'], ['ᨎ'],
          ['ヮ'], ['╭͜ʖ╮'], [' ͟ل͜'], [' ͜ʖ'], [' ͟ʖ'], [' ʖ̯'], ['ω'], [' ³'],
          [' ε '], ['﹏'], ['□'], ['ل͜'], ['‿'], ['╭╮'], ['‿‿'], ['▾'], ['‸'],
          ['Д'], ['∀'], ['!'], ['人'], ['.'], ['ロ'], ['_'], ['෴'], ['ѽ'], ['ഌ'],
          ['⏠'], ['⏏'], ['⍊'], ['⍘'], ['ツ'], ['益'], ['╭∩╮'], ['Ĺ̯'], ['◡'],
          [' ͜つ']]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

WAIFUS_IMG = (
      "https://telegra.ph/file/1ec63f252688e357fe5dc.jpg", 
      "https://telegra.ph/file/396dfa8da0a1ec173d216.jpg", 
      "https://telegra.ph/file/13f3035f7c9721a7c4037.jpg", 
      "https://telegra.ph/file/b625ec94c9992f3c234e2.jpg", 
      "https://telegra.ph/file/1dbab3a956f0f5acb81bd.jpg", 
      "https://telegra.ph/file/fe7b3dbd7d7756c081089.jpg", 
      "https://telegra.ph/file/a79cfc55901b11484ae39.jpg", 
      "https://telegra.ph/file/55eb767c3620e2dd0e38b.jpg", 
      "https://telegra.ph/file/11e055c5dea33a0775ded.jpg", 
      "https://telegra.ph/file/d01d49f4046b3b0f062e7.jpg", 
      "https://telegra.ph/file/a5bf691f5489989af0735.jpg", 
      "https://telegra.ph/file/6743afd2a0a1099a2d2be.jpg", 
      "https://telegra.ph/file/67b42f63fd2161a272eb6.jpg", 
      "https://telegra.ph/file/c927f1bd8e617e1fee3c2.jpg", 
      "https://telegra.ph/file/3619f8e3e667db5f65f4f.jpg", 
      "https://telegra.ph/file/d7e2b380fa20f62639f98.jpg", 
      "https://telegra.ph/file/5f20cc2e3873aa87c8fd7.jpg", 
      "https://telegra.ph/file/11af554a4a40eaeec044b.jpg", 
      "https://telegra.ph/file/c71acb1b6f27e7513cf8d.jpg", 
      "https://telegra.ph/file/0c41afe50d4314be7782b.jpg", 
      "https://telegra.ph/file/34f72bef3494681b2fe01.jpg", 
      "https://telegra.ph/file/3175d401e99cd34dd742e.jpg", 
      "https://telegra.ph/file/119984b824e246159bb2e.jpg", 
      "https://telegra.ph/file/cd2dd90422d70b1a0a69c.jpg", 
      "https://telegra.ph/file/fded74f953443e4564c07.jpg", 
      "https://telegra.ph/file/b23fe6ed1b92bd865aa31.jpg", 
      "https://telegra.ph/file/d5f6e2e907d54378597f5.jpg", 
      "https://telegra.ph/file/5784c50b2fffcad968fd0.jpg", 
      "https://telegra.ph/file/1addb904a7a3fdb5ebee5.jpg", 
      "https://telegra.ph/file/b83e4c2d001b53c45b7ae.jpg", 
      "https://telegra.ph/file/b5c31403c41bf4facc2b4.jpg", 
      "https://telegra.ph/file/ec9791a95c5bdf685308f.jpg", 
      "https://telegra.ph/file/5989a8819995b4534aebb.jpg", 
      "https://telegra.ph/file/4e0dda0411cff833a11b5.jpg", 
      "https://telegra.ph/file/7a41db0293929347cc215.jpg", 
      "https://telegra.ph/file/4b9df31690ebf46474eb6.jpg", 
      "https://telegra.ph/file/11f6fe6fb8919affb2198.jpg", 
      "https://telegra.ph/file/fa49a0900f25c0660ad93.jpg", 
      "https://telegra.ph/file/3d1659f0d97ad5bcd410c.jpg", 
      "https://telegra.ph/file/612301ecda86f1b8ac793.jpg", 
      "https://telegra.ph/file/77dae9e709aae0cfffa9e.jpg", 
      "https://telegra.ph/file/3025f16d9a138bd3e50bd.jpg", 
      "https://telegra.ph/file/29b44855ea256377a58b9.jpg", 
      "https://telegra.ph/file/3f000436110eb5a37328d.jpg", 
      "https://telegra.ph/file/d259fccb391b239f5f6cc.jpg", 
      "https://telegra.ph/file/9975315014c4bed41355c.jpg", 
      "https://telegra.ph/file/4f2ffecd983e8ec79d562.jpg", 
      "https://telegra.ph/file/98cac7e13e641499fcdf6.jpg", 
      "https://telegra.ph/file/631fce8620ebef937610a.jpg", 
      "https://telegra.ph/file/eff2fccf7e01f094d9086.jpg", 
      "https://telegra.ph/file/6ccb648036446425b3b8d.jpg", 
      "https://telegra.ph/file/6773a061fdc1d55386106.jpg", 
      "https://telegra.ph/file/abdf8a78c105790bf6934.jpg", 
      "https://telegra.ph/file/52249e7f70f27523df60f.jpg", 
      "https://telegra.ph/file/b25de0752d3a34026d437.jpg", 
      "https://telegra.ph/file/bbd0fb77fa3d00d8a27b3.jpg", 
      "https://telegra.ph/file/c69c55dca0f727eef3d57.jpg", 
      "https://telegra.ph/file/45e594a4f6bc2de05553c.jpg", 
      "https://telegra.ph/file/412ed1db500fa0ab73d71.jpg", 
      "https://telegra.ph/file/b235cf0b6533a7886efc7.jpg", 
      "https://telegra.ph/file/eedeb390e00ab929e85ec.jpg", 
      "https://telegra.ph/file/3e8009e5cd9cf63c58cf9.jpg", 
      "https://telegra.ph/file/f67753ca2a9e5888f281b.jpg", 
      "https://telegra.ph/file/e0c9d4f26765795ca8fa5.jpg", 
      "https://telegra.ph/file/f17cfc179b6c485af9ac6.jpg",
      "https://telegra.ph/file/64cbf01dbfed13265441b.jpg",
      "https://telegra.ph/file/35ab68cfeaa586dd754d2.jpg",
      "https://telegra.ph/file/b8105b1582f7d1877a771.jpg",
      "https://telegra.ph/file/36a6ca3c094f2246b6dee.jpg"
      
      )

GBUN = (
    "Beware! This Bot-Admeme Can Gbun You Right Off The Map.",
    "I Guess You've Forgot Spelling Of GBAN Maybe...?",
    "Don't Misuse Your Powers...",
    "Nah, He Looks Innocent...",
)


GBAM =  "#GBAMMED\n *Originated from:* `{chatid}`\n *Admin:* {user1}\n *Bammed User:* {user2}\n *Reason:* `{reason}`\n *Bammed User id*: `{user_chat.id}`\n *Event Stamp*: `{current_time}`"


GBAM_REASON = (
    "noob Mental",
    "white-het heking Mental",
    "white-het codur Mental",
    "Beger, Begging to call him pro",
    "fri-fire Mental",
    "Copycats",
    "Waifu Stealer",
    "Serial watcher",
    "Chota bheem Mental",
    "Tik tok Mental",
    "Pubg Mental",
    "Hexa Mental",
    "Crazy Bitch",
    "Gay boy",
    "Repo stealer",
)

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = ("No.", "Don't Ask Me.", "Yes.", "I Don't know.")

TABLE = ("(╯°□°）╯彡 ┻━┻", "I ran out of tables, will order more.",
         "Go do some work instead of flippin tables.")
